# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cad65e60562df9cbff67952fa356b585f5c3057419a1c7045079a4cbc7b8eaafb6f0765c4405e951c05a10bfead7a4e8ed299b3048fd279be86910301ca61832

test:
  secret_key_base: 04e01817d1096496fe7213b29c39b131cb0c0423b6fa790f8d28eb19fdede9a6b930487a5ed6fd4b19426f446e495ab97fc57828f50acb7f7a059cc537969426

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
